### ISSUE TITLE
Hints for adding additional metrics?

### ISSUE THREAD

**Issue by maplesteve** [tomgi/git_stats#5]
Hi!

Great work - thanks a lot!

I would like to add some more metrics (lines of comments etc.).
Do you have a brief explanation where additional commands should be implemented? Are there central places to call them, code to reuse with new input etc.

Thanks & best regards.

**Comment by hthappy** [comment]
hi,
Prompt "reading log message from standard input", always stuck in the interface, what is the reason?

Thanks & best regards.
