### ISSUE TITLE
Specify a start revsion

### ISSUE THREAD

**Issue by nickbroon** [tomgi/git_stats#9]
I have repo that have initial revision that consists of the import of the source from a project. This initial revision will usually be huge and result in it swamping all other revisions in charts and graphs.
It would be nice if the git_stats binary would accept a start revision to generate statistics from. 
(I suppose a end revision might also be useful to provide a complete range, though usually a clone can be made just up to the revision of interest)

**Comment by szgmwill** [comment]
hey guys. i want to filter the result with date range, how can i do this
